Description: >
    Cesarin Abreu: 
    Deploying Bastion Host Servers.
    Please provide a pair key and your IP in the apropriate parmaters.
    Remember that the servers that we need to access need their own pair key.
Parameters:
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    PersonalIP: 
        Description: Local IP adress that can connect to bastion 
        Type: String
        Default: 10.0.0.0/16 
    BastionKeyName: 
      Description: Amazon EC2 Key Pair
      Type: "AWS::EC2::KeyPair::KeyName"

Resources:
  BastionInstance:
      Type: 'AWS::EC2::Instance'
      Properties:
        ImageId: ami-003634241a8fcdec0 
        SecurityGroupIds:
        - Ref: BastionSecurityGroup
        InstanceType: t2.micro
        BlockDeviceMappings:
        - DeviceName: "/dev/sdk"
          Ebs:
            VolumeSize: '10'
        KeyName: !Ref BastionKeyName
        SubnetId:
          Fn::ImportValue: 
            !Sub "${EnvironmentName}-PUB-SN1"

  BastionSecurityGroup:
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
        GroupDescription: Enable SSH access to bastion via port 22 locally only
        VpcId:
                Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '22'
            ToPort: '22'
            CidrIp: !Ref PersonalIP
        SecurityGroupEgress:
            - IpProtocol: tcp
              FromPort: 0
              ToPort: 65535
              CidrIp: 0.0.0.0/0

Outputs:
  BastionInstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value:
      Ref: BastionInstance

  BastionPublicIP:
      Description: Public IP address of the newly created EC2 instance
      Value:
        Fn::GetAtt:
        - BastionInstance
        - PublicIp
      Export:
            Name: !Sub ${EnvironmentName}-BastionPublicIP